services:
  next-app:
    container_name: personal-website
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    #      - /app/node_modules  # Prevent overwriting node_modules
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: ["pnpm", "dev"]
