import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Analytics} from "@vercel/analytics/react"
import {SpeedInsights} from "@vercel/speed-insights/next"
import {ThemeProvider} from "@/components/theme-provider";
import {ModeToggle} from "@/components/ui/mode-toggle";
import {Header} from "@/components/header/header";
import {BackgroundBeamsWithCollision} from "@/components/background-beams-with-collision";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true} className="scroll-smooth light">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <BackgroundBeamsWithCollision>
                <Header/>
                {children}
                <div className={" fixed bottom-6 right-6"}>
                    <ModeToggle/>
                </div>
            </BackgroundBeamsWithCollision>
        </ThemeProvider>
        <Analytics/>
        <SpeedInsights/>
        </body>
        </html>
    );
}
